import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Aditya's Portfolio",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div><h1>uuu</h1></div>
  )
}

export default page